<a href="https://colab.research.google.com/github/mothukuriv/ML/blob/master/ML_programing_A2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:

# Importing the dataset
dataset = pd.read_csv('Bank_Predictions.csv')

In [0]:
dataset.head()

   Number  Customer_ID Last_Name  ...  IsActiveMember Customer_Salary Acc_Closed
0       1     15634602  Hargrave  ...               1       101348.88          1
1       2     15647311      Hill  ...               1       112542.58          0
2       3     15619304      Onio  ...               0       113931.57          1
3       4     15701354      Boni  ...               0        93826.63          0
4       5     15737888  Mitchell  ...               1        79084.10          0

[5 rows x 14 columns]

In [0]:
dataset

      Number  Customer_ID  ... Customer_Salary  Acc_Closed
0          1     15634602  ...       101348.88           1
1          2     15647311  ...       112542.58           0
2          3     15619304  ...       113931.57           1
3          4     15701354  ...        93826.63           0
4          5     15737888  ...        79084.10           0
...      ...          ...  ...             ...         ...
9995    9996     15606229  ...        96270.64           0
9996    9997     15569892  ...       101699.77           0
9997    9998     15584532  ...        42085.58           1
9998    9999     15682355  ...        92888.52           1
9999   10000     15628319  ...        38190.78           0

[10000 rows x 14 columns]

In [0]:
# Encoding categorical data
dataset.drop(columns = ['Number', 'Customer_ID', 'Last_Name'])

      Cr_Score Location  Gender  ...  IsActiveMember  Customer_Salary  Acc_Closed
0          619   France  Female  ...               1        101348.88           1
1          608    Spain  Female  ...               1        112542.58           0
2          502   France  Female  ...               0        113931.57           1
3          699   France  Female  ...               0         93826.63           0
4          850    Spain  Female  ...               1         79084.10           0
...        ...      ...     ...  ...             ...              ...         ...
9995       771   France    Male  ...               0         96270.64           0
9996       516   France    Male  ...               1        101699.77           0
9997       709   France  Female  ...               1         42085.58           1
9998       772  Germany    Male  ...               0         92888.52           1
9999       792   France  Female  ...               0         38190.78           0

[10000 rows x 11 columns]

In [0]:
np.array(dataset.drop(columns = ['Number', 'Customer_ID', 'Last_Name']))

array([[619, 'France', 'Female', ..., 1, 101348.88, 1],
       [608, 'Spain', 'Female', ..., 1, 112542.58, 0],
       [502, 'France', 'Female', ..., 0, 113931.57, 1],
       ...,
       [709, 'France', 'Female', ..., 1, 42085.58, 1],
       [772, 'Germany', 'Male', ..., 0, 92888.52, 1],
       [792, 'France', 'Female', ..., 0, 38190.78, 0]], dtype=object)

In [0]:
np.array(dataset['Acc_Closed'])

array([1, 0, 1, ..., 1, 1, 0])

In [0]:
X = dataset.iloc[:, 3:13].values
Y = dataset.iloc[:, 13].values

In [0]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [0]:

from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

label_encoder = LabelEncoder()

X[:,1] = label_encoder.fit_transform(X[:,1])
X[:,2] = label_encoder.fit_transform(X[:,2])

In [0]:
X, Y

(array([[619, 0, 0, ..., 1, 1, 101348.88],
        [608, 2, 0, ..., 0, 1, 112542.58],
        [502, 0, 0, ..., 1, 0, 113931.57],
        ...,
        [709, 0, 0, ..., 0, 1, 42085.58],
        [772, 1, 1, ..., 1, 0, 92888.52],
        [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object),
 array([1, 0, 1, ..., 1, 1, 0]))

In [0]:
transformer = ColumnTransformer(
    transformers=[
        ("hc",   
         OneHotEncoder(), 
         [1]             
         )
    ],
    remainder = 'passthrough'
)
X = transformer.fit_transform(X)

In [0]:
X = X[:, 1:]

In [0]:
# Splitting the dataset into the Training and Test sets

# Feature Scaling
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

X_train = scale.fit_transform(X_train)
X_test = scale.transform(X_test)

In [0]:
# ------- Part-2: Build the ANN --------

# import keras library and packages
import keras

from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.

In [0]:
# Initializing the ANN

classifier = Sequential()

In [0]:

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11 ))

# Adding second hidden layer

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [0]:
# Compiling the ANN
classifier.compile(optimizer = 'adam',loss= "binary_crossentropy", metrics=["accuracy"])

In [0]:
# Fitting the ANN to the training set
classifier.fit(X_train, Y_train, batch_size = 10, epochs = 200  )

Epoch 1/200
7000/7000 [==============================] - 1s 117us/step - loss: 0.3953 - acc: 0.8363
Epoch 2/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3950 - acc: 0.8363
Epoch 3/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3945 - acc: 0.8374
Epoch 4/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3946 - acc: 0.8373
Epoch 5/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3946 - acc: 0.8367
Epoch 6/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3944 - acc: 0.8386
Epoch 7/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3943 - acc: 0.8376
Epoch 8/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3941 - acc: 0.8374
Epoch 9/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3938 - acc: 0.8377
Epoch 10/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3935 - acc: 0.8389
Epoch 11/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3938 - acc: 0.8369
Epoch 12/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3936 - acc: 0.8377
Epoch 13/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3924 - acc: 0.8387
Epoch 14/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3929 - acc: 0.8370
Epoch 15/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3925 - acc: 0.8366
Epoch 16/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3933 - acc: 0.8370
Epoch 17/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3929 - acc: 0.8386
Epoch 18/200
7000/7000 [==============================] - 1s 111us/step - loss: 0.3923 - acc: 0.8369
Epoch 19/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3920 - acc: 0.8394
Epoch 20/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3915 - acc: 0.8369
Epoch 21/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3902 - acc: 0.8377
Epoch 22/200
7000/7000 [==============================] - 1s 111us/step - loss: 0.3894 - acc: 0.8396
Epoch 23/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3871 - acc: 0.8393
Epoch 24/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3854 - acc: 0.8386
Epoch 25/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3841 - acc: 0.8393
Epoch 26/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3824 - acc: 0.8376
Epoch 27/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3810 - acc: 0.8364
Epoch 28/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3800 - acc: 0.8369
Epoch 29/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3789 - acc: 0.8391
Epoch 30/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3782 - acc: 0.8386
Epoch 31/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3781 - acc: 0.8381
Epoch 32/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3770 - acc: 0.8353
Epoch 33/200
7000/7000 [==============================] - 1s 118us/step - loss: 0.3766 - acc: 0.8349
Epoch 34/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3774 - acc: 0.8354
Epoch 35/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3763 - acc: 0.8369
Epoch 36/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3757 - acc: 0.8391
Epoch 37/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3762 - acc: 0.8371
Epoch 38/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3752 - acc: 0.8366
Epoch 39/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3749 - acc: 0.8377
Epoch 40/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3748 - acc: 0.8359
Epoch 41/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3743 - acc: 0.8386
Epoch 42/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3744 - acc: 0.8394
Epoch 43/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3735 - acc: 0.8387
Epoch 44/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3739 - acc: 0.8390
Epoch 45/200
7000/7000 [==============================] - 1s 118us/step - loss: 0.3732 - acc: 0.8381
Epoch 46/200
7000/7000 [==============================] - 1s 119us/step - loss: 0.3731 - acc: 0.8381
Epoch 47/200
7000/7000 [==============================] - 1s 117us/step - loss: 0.3730 - acc: 0.8407
Epoch 48/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3727 - acc: 0.8384
Epoch 49/200
7000/7000 [==============================] - 1s 117us/step - loss: 0.3721 - acc: 0.8373
Epoch 50/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3724 - acc: 0.8391
Epoch 51/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3723 - acc: 0.8391
Epoch 52/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3715 - acc: 0.8394
Epoch 53/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3721 - acc: 0.8406
Epoch 54/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3713 - acc: 0.8419
Epoch 55/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3699 - acc: 0.8414
Epoch 56/200
7000/7000 [==============================] - 1s 119us/step - loss: 0.3709 - acc: 0.8397
Epoch 57/200
7000/7000 [==============================] - 1s 117us/step - loss: 0.3715 - acc: 0.8413
Epoch 58/200
7000/7000 [==============================] - 1s 119us/step - loss: 0.3706 - acc: 0.8413
Epoch 59/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3712 - acc: 0.8403
Epoch 60/200
7000/7000 [==============================] - 1s 118us/step - loss: 0.3702 - acc: 0.8423
Epoch 61/200
7000/7000 [==============================] - 1s 117us/step - loss: 0.3701 - acc: 0.8410
Epoch 62/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3707 - acc: 0.8414
Epoch 63/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3699 - acc: 0.8409
Epoch 64/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3708 - acc: 0.8406
Epoch 65/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3700 - acc: 0.8403
Epoch 66/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3695 - acc: 0.8400
Epoch 67/200
7000/7000 [==============================] - 1s 109us/step - loss: 0.3700 - acc: 0.8420
Epoch 68/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3699 - acc: 0.8400
Epoch 69/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3694 - acc: 0.8439
Epoch 70/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3697 - acc: 0.8393
Epoch 71/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3695 - acc: 0.8404
Epoch 72/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3694 - acc: 0.8397
Epoch 73/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3695 - acc: 0.8404
Epoch 74/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3690 - acc: 0.8413
Epoch 75/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3692 - acc: 0.8404
Epoch 76/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3688 - acc: 0.8419
Epoch 77/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3691 - acc: 0.8419
Epoch 78/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3688 - acc: 0.8407
Epoch 79/200
7000/7000 [==============================] - 1s 111us/step - loss: 0.3687 - acc: 0.8420
Epoch 80/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3685 - acc: 0.8443
Epoch 81/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3690 - acc: 0.8423
Epoch 82/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3680 - acc: 0.8424
Epoch 83/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3688 - acc: 0.8423
Epoch 84/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3690 - acc: 0.8396
Epoch 85/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3680 - acc: 0.8410
Epoch 86/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3677 - acc: 0.8430
Epoch 87/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3686 - acc: 0.8416
Epoch 88/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3678 - acc: 0.8407
Epoch 89/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3684 - acc: 0.8404
Epoch 90/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3681 - acc: 0.8420
Epoch 91/200
7000/7000 [==============================] - 1s 111us/step - loss: 0.3678 - acc: 0.8420
Epoch 92/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3673 - acc: 0.8420
Epoch 93/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3680 - acc: 0.8401
Epoch 94/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3677 - acc: 0.8430
Epoch 95/200
7000/7000 [==============================] - 1s 111us/step - loss: 0.3673 - acc: 0.8414
Epoch 96/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3681 - acc: 0.8406
Epoch 97/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3677 - acc: 0.8437
Epoch 98/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3673 - acc: 0.8421
Epoch 99/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3679 - acc: 0.8429
Epoch 100/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3666 - acc: 0.8417
Epoch 101/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3673 - acc: 0.8409
Epoch 102/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3677 - acc: 0.8413
Epoch 103/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3677 - acc: 0.8404
Epoch 104/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3661 - acc: 0.8439
Epoch 105/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3674 - acc: 0.8419
Epoch 106/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3677 - acc: 0.8437
Epoch 107/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3671 - acc: 0.8413
Epoch 108/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3674 - acc: 0.8414
Epoch 109/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3669 - acc: 0.8434
Epoch 110/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3669 - acc: 0.8426
Epoch 111/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3674 - acc: 0.8429
Epoch 112/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3673 - acc: 0.8411
Epoch 113/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3667 - acc: 0.8433
Epoch 114/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3658 - acc: 0.8409
Epoch 115/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3673 - acc: 0.8406
Epoch 116/200
7000/7000 [==============================] - 1s 111us/step - loss: 0.3665 - acc: 0.8436
Epoch 117/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3672 - acc: 0.8424
Epoch 118/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3667 - acc: 0.8433
Epoch 119/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3664 - acc: 0.8439
Epoch 120/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3662 - acc: 0.8437
Epoch 121/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3661 - acc: 0.8414
Epoch 122/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3659 - acc: 0.8444
Epoch 123/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3663 - acc: 0.8431
Epoch 124/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3662 - acc: 0.8433
Epoch 125/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3669 - acc: 0.8439
Epoch 126/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3661 - acc: 0.8443
Epoch 127/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3670 - acc: 0.8420
Epoch 128/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3662 - acc: 0.8443
Epoch 129/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3662 - acc: 0.8424
Epoch 130/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3662 - acc: 0.8426
Epoch 131/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3655 - acc: 0.8461
Epoch 132/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3656 - acc: 0.8446
Epoch 133/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3651 - acc: 0.8434
Epoch 134/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3655 - acc: 0.8440
Epoch 135/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3655 - acc: 0.8437
Epoch 136/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3651 - acc: 0.8467
Epoch 137/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3649 - acc: 0.8440
Epoch 138/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3653 - acc: 0.8466
Epoch 139/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3652 - acc: 0.8453
Epoch 140/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3655 - acc: 0.8450
Epoch 141/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3645 - acc: 0.8437
Epoch 142/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3655 - acc: 0.8413
Epoch 143/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3657 - acc: 0.8454
Epoch 144/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3655 - acc: 0.8437
Epoch 145/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3656 - acc: 0.8456
Epoch 146/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3650 - acc: 0.8456
Epoch 147/200
7000/7000 [==============================] - 1s 117us/step - loss: 0.3655 - acc: 0.8433
Epoch 148/200
7000/7000 [==============================] - 1s 111us/step - loss: 0.3658 - acc: 0.8453
Epoch 149/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3655 - acc: 0.8446
Epoch 150/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3649 - acc: 0.8453
Epoch 151/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3650 - acc: 0.8463
Epoch 152/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3649 - acc: 0.8454
Epoch 153/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3656 - acc: 0.8441
Epoch 154/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3648 - acc: 0.8447
Epoch 155/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3649 - acc: 0.8427
Epoch 156/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3647 - acc: 0.8440
Epoch 157/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3652 - acc: 0.8439
Epoch 158/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3650 - acc: 0.8463
Epoch 159/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3653 - acc: 0.8447
Epoch 160/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3650 - acc: 0.8439
Epoch 161/200
7000/7000 [==============================] - 1s 118us/step - loss: 0.3653 - acc: 0.8437
Epoch 162/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3640 - acc: 0.8454
Epoch 163/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3654 - acc: 0.8447
Epoch 164/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3651 - acc: 0.8469
Epoch 165/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3656 - acc: 0.8447
Epoch 166/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3654 - acc: 0.8450
Epoch 167/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3652 - acc: 0.8446
Epoch 168/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3643 - acc: 0.8447
Epoch 169/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3642 - acc: 0.8443
Epoch 170/200
7000/7000 [==============================] - 1s 111us/step - loss: 0.3653 - acc: 0.8460
Epoch 171/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3654 - acc: 0.8463
Epoch 172/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3650 - acc: 0.8437
Epoch 173/200
7000/7000 [==============================] - 1s 117us/step - loss: 0.3648 - acc: 0.8477
Epoch 174/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3646 - acc: 0.8437
Epoch 175/200
7000/7000 [==============================] - 1s 115us/step - loss: 0.3645 - acc: 0.8453
Epoch 176/200
7000/7000 [==============================] - 1s 117us/step - loss: 0.3646 - acc: 0.8460
Epoch 177/200
7000/7000 [==============================] - 1s 117us/step - loss: 0.3641 - acc: 0.8476
Epoch 178/200
7000/7000 [==============================] - 1s 111us/step - loss: 0.3645 - acc: 0.8440
Epoch 179/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3644 - acc: 0.8454
Epoch 180/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3649 - acc: 0.8460
Epoch 181/200
7000/7000 [==============================] - 1s 114us/step - loss: 0.3645 - acc: 0.8457
Epoch 182/200
7000/7000 [==============================] - 1s 116us/step - loss: 0.3642 - acc: 0.8460
Epoch 183/200
7000/7000 [==============================] - 1s 112us/step - loss: 0.3648 - acc: 0.8444
Epoch 184/200
7000/7000 [==============================] - 1s 117us/step - loss: 0.3646 - acc: 0.8454
Epoch 185/200
7000/7000 [==============================] - 1s 113us/step - loss: 0.3649 - acc: 0.8453
Epoch 186/200
7000/7000 [==============================] - 1s 120us/step - loss: 0.3645 - acc: 0.8463
Epoch 187/200
7000/7000 [==============================] - 1s 125us/step - loss: 0.3644 - acc: 0.8449
Epoch 188/200
7000/7000 [==============================] - 1s 123us/step - loss: 0.3649 - acc: 0.8436
Epoch 189/200
7000/7000 [==============================] - 1s 125us/step - loss: 0.3647 - acc: 0.8457
Epoch 190/200
7000/7000 [==============================] - 1s 122us/step - loss: 0.3646 - acc: 0.8454
Epoch 191/200
7000/7000 [==============================] - 1s 123us/step - loss: 0.3638 - acc: 0.8459
Epoch 192/200
7000/7000 [==============================] - 1s 128us/step - loss: 0.3652 - acc: 0.8439
Epoch 193/200
7000/7000 [==============================] - 1s 121us/step - loss: 0.3644 - acc: 0.8426
Epoch 194/200
7000/7000 [==============================] - 1s 126us/step - loss: 0.3649 - acc: 0.8476
Epoch 195/200
7000/7000 [==============================] - 1s 126us/step - loss: 0.3651 - acc: 0.8444
Epoch 196/200
7000/7000 [==============================] - 1s 125us/step - loss: 0.3646 - acc: 0.8449
Epoch 197/200
7000/7000 [==============================] - 1s 124us/step - loss: 0.3649 - acc: 0.8437
Epoch 198/200

In [0]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [0]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [0]:

# Making the confusion Matrix

from sklearn.metrics import confusion_matrix
output_matrix = confusion_matrix(Y_test, y_pred)

In [0]:
output_matrix

array([[2262,  117],
       [ 354,  267]])